//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IT_Final_Year_Lohaghat.ITFinalYearWebServices {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://gplohaghat.org.in/ITFinalWS", ConfigurationName="ITFinalYearWebServices.ITFinalWebServiceSoap")]
    public interface ITFinalWebServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gplohaghat.org.in/ITFinalWS/GetDataSet", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetDataSet(string connString, string queryString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gplohaghat.org.in/ITFinalWS/GetDataSet", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetDataSetAsync(string connString, string queryString);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITFinalWebServiceSoapChannel : IT_Final_Year_Lohaghat.ITFinalYearWebServices.ITFinalWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TFinalWebServiceSoapClient : System.ServiceModel.ClientBase<IT_Final_Year_Lohaghat.ITFinalYearWebServices.ITFinalWebServiceSoap>, IT_Final_Year_Lohaghat.ITFinalYearWebServices.ITFinalWebServiceSoap {
        
        public TFinalWebServiceSoapClient() {
        }
        
        public TFinalWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TFinalWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TFinalWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TFinalWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet GetDataSet(string connString, string queryString) {
            return base.Channel.GetDataSet(connString, queryString);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetDataSetAsync(string connString, string queryString) {
            return base.Channel.GetDataSetAsync(connString, queryString);
        }
    }
}
