//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IT_Final_Year_Lohaghat.ITFinalGPLG {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://gplohagat.org.in/ITFinal", ConfigurationName="ITFinalGPLG.ITFinalLohaghatSoap")]
    public interface ITFinalLohaghatSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace https://gplohagat.org.in/ITFinal is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="https://gplohagat.org.in/ITFinal/HelloWorld", ReplyAction="*")]
        IT_Final_Year_Lohaghat.ITFinalGPLG.HelloWorldResponse HelloWorld(IT_Final_Year_Lohaghat.ITFinalGPLG.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://gplohagat.org.in/ITFinal/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<IT_Final_Year_Lohaghat.ITFinalGPLG.HelloWorldResponse> HelloWorldAsync(IT_Final_Year_Lohaghat.ITFinalGPLG.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name GetInstituteInformationResult from namespace https://gplohagat.org.in/ITFinal is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="https://gplohagat.org.in/ITFinal/GetInstituteInformation", ReplyAction="*")]
        IT_Final_Year_Lohaghat.ITFinalGPLG.GetInstituteInformationResponse GetInstituteInformation(IT_Final_Year_Lohaghat.ITFinalGPLG.GetInstituteInformationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://gplohagat.org.in/ITFinal/GetInstituteInformation", ReplyAction="*")]
        System.Threading.Tasks.Task<IT_Final_Year_Lohaghat.ITFinalGPLG.GetInstituteInformationResponse> GetInstituteInformationAsync(IT_Final_Year_Lohaghat.ITFinalGPLG.GetInstituteInformationRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="https://gplohagat.org.in/ITFinal", Order=0)]
        public IT_Final_Year_Lohaghat.ITFinalGPLG.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(IT_Final_Year_Lohaghat.ITFinalGPLG.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="https://gplohagat.org.in/ITFinal", Order=0)]
        public IT_Final_Year_Lohaghat.ITFinalGPLG.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(IT_Final_Year_Lohaghat.ITFinalGPLG.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://gplohagat.org.in/ITFinal")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetInstituteInformationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetInstituteInformation", Namespace="https://gplohagat.org.in/ITFinal", Order=0)]
        public IT_Final_Year_Lohaghat.ITFinalGPLG.GetInstituteInformationRequestBody Body;
        
        public GetInstituteInformationRequest() {
        }
        
        public GetInstituteInformationRequest(IT_Final_Year_Lohaghat.ITFinalGPLG.GetInstituteInformationRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://gplohagat.org.in/ITFinal")]
    public partial class GetInstituteInformationRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int instCode;
        
        public GetInstituteInformationRequestBody() {
        }
        
        public GetInstituteInformationRequestBody(int instCode) {
            this.instCode = instCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetInstituteInformationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetInstituteInformationResponse", Namespace="https://gplohagat.org.in/ITFinal", Order=0)]
        public IT_Final_Year_Lohaghat.ITFinalGPLG.GetInstituteInformationResponseBody Body;
        
        public GetInstituteInformationResponse() {
        }
        
        public GetInstituteInformationResponse(IT_Final_Year_Lohaghat.ITFinalGPLG.GetInstituteInformationResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://gplohagat.org.in/ITFinal")]
    public partial class GetInstituteInformationResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetInstituteInformationResult;
        
        public GetInstituteInformationResponseBody() {
        }
        
        public GetInstituteInformationResponseBody(string GetInstituteInformationResult) {
            this.GetInstituteInformationResult = GetInstituteInformationResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITFinalLohaghatSoapChannel : IT_Final_Year_Lohaghat.ITFinalGPLG.ITFinalLohaghatSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TFinalLohaghatSoapClient : System.ServiceModel.ClientBase<IT_Final_Year_Lohaghat.ITFinalGPLG.ITFinalLohaghatSoap>, IT_Final_Year_Lohaghat.ITFinalGPLG.ITFinalLohaghatSoap {
        
        public TFinalLohaghatSoapClient() {
        }
        
        public TFinalLohaghatSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TFinalLohaghatSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TFinalLohaghatSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TFinalLohaghatSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IT_Final_Year_Lohaghat.ITFinalGPLG.HelloWorldResponse IT_Final_Year_Lohaghat.ITFinalGPLG.ITFinalLohaghatSoap.HelloWorld(IT_Final_Year_Lohaghat.ITFinalGPLG.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            IT_Final_Year_Lohaghat.ITFinalGPLG.HelloWorldRequest inValue = new IT_Final_Year_Lohaghat.ITFinalGPLG.HelloWorldRequest();
            inValue.Body = new IT_Final_Year_Lohaghat.ITFinalGPLG.HelloWorldRequestBody();
            IT_Final_Year_Lohaghat.ITFinalGPLG.HelloWorldResponse retVal = ((IT_Final_Year_Lohaghat.ITFinalGPLG.ITFinalLohaghatSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IT_Final_Year_Lohaghat.ITFinalGPLG.HelloWorldResponse> IT_Final_Year_Lohaghat.ITFinalGPLG.ITFinalLohaghatSoap.HelloWorldAsync(IT_Final_Year_Lohaghat.ITFinalGPLG.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<IT_Final_Year_Lohaghat.ITFinalGPLG.HelloWorldResponse> HelloWorldAsync() {
            IT_Final_Year_Lohaghat.ITFinalGPLG.HelloWorldRequest inValue = new IT_Final_Year_Lohaghat.ITFinalGPLG.HelloWorldRequest();
            inValue.Body = new IT_Final_Year_Lohaghat.ITFinalGPLG.HelloWorldRequestBody();
            return ((IT_Final_Year_Lohaghat.ITFinalGPLG.ITFinalLohaghatSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IT_Final_Year_Lohaghat.ITFinalGPLG.GetInstituteInformationResponse IT_Final_Year_Lohaghat.ITFinalGPLG.ITFinalLohaghatSoap.GetInstituteInformation(IT_Final_Year_Lohaghat.ITFinalGPLG.GetInstituteInformationRequest request) {
            return base.Channel.GetInstituteInformation(request);
        }
        
        public string GetInstituteInformation(int instCode) {
            IT_Final_Year_Lohaghat.ITFinalGPLG.GetInstituteInformationRequest inValue = new IT_Final_Year_Lohaghat.ITFinalGPLG.GetInstituteInformationRequest();
            inValue.Body = new IT_Final_Year_Lohaghat.ITFinalGPLG.GetInstituteInformationRequestBody();
            inValue.Body.instCode = instCode;
            IT_Final_Year_Lohaghat.ITFinalGPLG.GetInstituteInformationResponse retVal = ((IT_Final_Year_Lohaghat.ITFinalGPLG.ITFinalLohaghatSoap)(this)).GetInstituteInformation(inValue);
            return retVal.Body.GetInstituteInformationResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IT_Final_Year_Lohaghat.ITFinalGPLG.GetInstituteInformationResponse> IT_Final_Year_Lohaghat.ITFinalGPLG.ITFinalLohaghatSoap.GetInstituteInformationAsync(IT_Final_Year_Lohaghat.ITFinalGPLG.GetInstituteInformationRequest request) {
            return base.Channel.GetInstituteInformationAsync(request);
        }
        
        public System.Threading.Tasks.Task<IT_Final_Year_Lohaghat.ITFinalGPLG.GetInstituteInformationResponse> GetInstituteInformationAsync(int instCode) {
            IT_Final_Year_Lohaghat.ITFinalGPLG.GetInstituteInformationRequest inValue = new IT_Final_Year_Lohaghat.ITFinalGPLG.GetInstituteInformationRequest();
            inValue.Body = new IT_Final_Year_Lohaghat.ITFinalGPLG.GetInstituteInformationRequestBody();
            inValue.Body.instCode = instCode;
            return ((IT_Final_Year_Lohaghat.ITFinalGPLG.ITFinalLohaghatSoap)(this)).GetInstituteInformationAsync(inValue);
        }
    }
}
